improved ReviewList/New Review, added link
masnottuh/Group-Project pull request #28
Opened 2023-03-22 14:06 UTC by lizcoats

2023-03-22 14:26 UTC, AaronShipman approved these changes

2023-03-22 22:03 UTC, masnottuh requested changes
no need to change the cors_origin_whitelist, it was [*] which allows all connections

2023-03-23 23:48 UTC, Sam-Zilli approved these changes

2023-03-23 23:48 UTC, Sam-Zilli approved these changes

2023-03-23 23:51 UTC, AaronShipman approved these changes

2023-03-23 23:51 UTC, AaronShipman approved these changes

2023-03-24 00:06 UTC, masnottuh approved these changes

2023-03-24 00:06 UTC, merged